services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    image: backend
    build: ./backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  postgres:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: postgres
