services:
  frontend:
    image: frontend
    build: ./frontend
    ports:
      - 5000:5000
    container_name: frontend
  backend:
    image: backend
    build: ./backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
